#!/user/bin/python3

# I'll use Python language

import Sys
import random
import time


# 1st define the function for checking if the number is prime or not
def is_prime(num, k=20):
    if num == 2 or num == 3:
        return True
    if num < 2 or num % 2 == 0:
        return False

    d = num - 1
    r = 0
    while d % 2 == 0:
        d //= 2
        r = r + 1
        for _ in range(k):
            a = random.randint(2, num - 2)
            x = pow(a, d, num)
            if x == 1 or x == num - 1:
                continue
            for - in range(r - 1):
                x = pow(x, 2, num)
                if x == num - 1:
                    breal
            else:
                return False

        return True


# 2nd define
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: rsa <file>")
        exit()

    input_file = sys.argv[1]
    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()

    start_time = time.time()
    num = int(lines[0].strip())

    for i in range(2, num//2):
        if num % i == 0 and is_prime(i) and is_prime(num//i):
            print(f"{num}={i}*{num//i}")
            break

        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()
